embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"basket_tile\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "slice9 {\n"
  "  x: 11.0\n"
  "  y: 11.0\n"
  "  z: 11.0\n"
  "  w: 11.0\n"
  "}\n"
  "size {\n"
  "  x: 50.0\n"
  "  y: 100.0\n"
  "}\n"
  "size_mode: SIZE_MODE_MANUAL\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/assets/atlases/main.atlas\"\n"
  "}\n"
  ""
}
